### ISSUE TITLE
HRRR Hindcast Test File Example

### ISSUE THREAD

**Issue by jduckerOWP** [waterinstitute/MetGet#15]
I am having trouble trying to create a MetGet data request for HRRR-Alaska hindcast data using the examples from the current repository (GFS example). Here is my Python module test case code below:

```python
from metget.metget_build import MetGetBuildRest
metget_server = "https://metget.server.org"
metget_api_key = "test_build_hrrr_alaska"
metget_api_version = 2
request_data = MetGetBuildRest.generate_request_json(analysis=True,multiple_forecasts=False,start_date="2020-04-15 00:00:00",end_date="2020-06-01 00:00:00",format="owi-netcdf",data_type={"wind_pressure", "rain", "temperature", "humidity"},backfill=False,time_step=3600,domains=[{"level":0,"name":"hrrr-alaska","service":"hrrr-alaska-ncep"}],compression=False,epsg=4326,filename="test_build_alaska_hrrr",strict=False,dry_run=False,save_json_request=False)
client = MetGetBuildRest(metget_server, metget_api_key, metget_api_version)
data_id, status_code = client.make_metget_request(request_data)
TypeError: Object of type set is not JSON serializable
```

Is there any way a hindcast HRRR-Alaska and/or HRRR-CONUS hindcast test case can be built for the MetGet community to guide us through an example like this? Ideally, I am trying to extract the entire HRRR domain for my data request, but maybe the issue is related to the "domain" specification not including all requested characteristics for the data extraction? Any assistance would be greatly appreciated!

**Comment by zcobell** [comment]
Hi @jduckerOWP - 

I think the issue with the above is that you're requesting multiple data types rather than a single data type. The current implementation of MetGet only allows a single data type per request. I've tested on this end and removing: `data_type={"wind_pressure", "rain", "temperature", "humidity"}` and instead setting it to `data_type="wind_pressure"` resolves the issue.

Other (likely intentional) issues are that you'll need to point the `metget_server` variable at an active instance of [metget-server](https://github.com/waterinstitute/metget-server) and populate the associated API key.

Let me know if that all works
